### ISSUE TITLE
The setter 'jsonProperties' isn't defined for the type 'Document'.

### ISSUE THREAD

**Issue by MilesHart** [Rudiksz/couchbase_lite_dart#15]
I'm getting this issues in the example. I'm sure I'm missing something simple. Any help would be appreciated.

The setter 'jsonProperties' isn't defined for the type 'Document'.
Try importing the library that defines 'jsonProperties', correcting the name to the name of an existing setter, or defining a setter or field named 'jsonProperties'.dart(undefined_setter

**Comment by Rudiksz** [comment]
It's called only `json`. I thought I fixed the example, but seems it came back.
