### ISSUE TITLE
lopen failed: library "libCouchbaseLiteC.so" not found

### ISSUE THREAD

**Issue by richard457** [Rudiksz/couchbase_lite_dart#4]
I added this to my pubspec file couchbase_lite_dart: ^0.2.0 then this 

```
Cbl.init();
var db = Database("testdb");

print(db.isOpen); 
```
And I am having the above error any help?

**Comment by Rudiksz** [comment]
Android shared libraries are not bundled with the package, you will need to add them to your project manually.
I updated the package with a few important fixes so make sure you use the v.0.3.0 version.
Check the updated README for details on how to get them and include them in your project.

**Comment by richard457** [comment]
Thank you, I got it working done some Test.
